package presentacion;

import entidades.*;
import javax.swing.*;
import java.util.ArrayList;
import com.formdev.flatlaf.FlatLightLaf;
public class FormHabitacion extends javax.swing.JFrame {

    /**
     * Creates new form FormHabitacion
     */
    public FormHabitacion() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitulo = new javax.swing.JLabel();
        lblEstado = new javax.swing.JLabel();
        txtEstado = new javax.swing.JTextField();
        btnRegistrarEst = new javax.swing.JButton();
        btnBorrar = new javax.swing.JButton();
        lblSubtituloInfoH = new javax.swing.JLabel();
        lblNombre = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        lblApellidos = new javax.swing.JLabel();
        txtApellido = new javax.swing.JTextField();
        txtTipoDoc = new javax.swing.JTextField();
        lblTipoDoc = new javax.swing.JLabel();
        txtNumDoc = new javax.swing.JTextField();
        lblTipoDoc1 = new javax.swing.JLabel();
        txtNumDoc1 = new javax.swing.JTextField();
        lblTipoDoc2 = new javax.swing.JLabel();
        txtNumDoc3 = new javax.swing.JTextField();
        lblFechaIngreso = new javax.swing.JLabel();
        txtNumDoc4 = new javax.swing.JTextField();
        lblDiasReserva = new javax.swing.JLabel();
        btnCambiarReserva = new javax.swing.JButton();
        btnRegistrarServicio = new javax.swing.JButton();
        btnRegistrarAcompa = new javax.swing.JButton();
        btnVolver = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Menú de Habitación");
        setResizable(false);

        lblTitulo.setFont(new java.awt.Font("Cantarell", 1, 22)); // NOI18N
        lblTitulo.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblTitulo.setText("Menú de Habitación");

        lblEstado.setFont(new java.awt.Font("Cantarell", 0, 15)); // NOI18N
        lblEstado.setText("Estado:");

        txtEstado.setEditable(false);
        txtEstado.setFont(new java.awt.Font("Cantarell", 0, 15)); // NOI18N

        btnRegistrarEst.setFont(new java.awt.Font("Cantarell", 0, 15)); // NOI18N
        btnRegistrarEst.setText("Registrar Estadía");

        btnBorrar.setFont(new java.awt.Font("Cantarell", 0, 15)); // NOI18N
        btnBorrar.setText("Borrar Estadía");

        lblSubtituloInfoH.setFont(new java.awt.Font("Cantarell", 1, 10)); // NOI18N
        lblSubtituloInfoH.setText("INFORMACIÓN DEL HUÉSPED PRINCIPAL");

        lblNombre.setFont(new java.awt.Font("Cantarell", 0, 16)); // NOI18N
        lblNombre.setText("Nombre(s):");

        txtNombre.setEditable(false);
        txtNombre.setFont(new java.awt.Font("Cantarell", 0, 16)); // NOI18N

        lblApellidos.setFont(new java.awt.Font("Cantarell", 0, 16)); // NOI18N
        lblApellidos.setText("Apellidos:");

        txtApellido.setEditable(false);
        txtApellido.setFont(new java.awt.Font("Cantarell", 0, 16)); // NOI18N

        txtTipoDoc.setEditable(false);
        txtTipoDoc.setFont(new java.awt.Font("Cantarell", 0, 16)); // NOI18N

        lblTipoDoc.setFont(new java.awt.Font("Cantarell", 0, 16)); // NOI18N
        lblTipoDoc.setText("Tipo de Documento:");

        txtNumDoc.setEditable(false);
        txtNumDoc.setFont(new java.awt.Font("Cantarell", 0, 16)); // NOI18N

        lblTipoDoc1.setFont(new java.awt.Font("Cantarell", 0, 16)); // NOI18N
        lblTipoDoc1.setText("Número de Doc. ID:");

        txtNumDoc1.setEditable(false);
        txtNumDoc1.setFont(new java.awt.Font("Cantarell", 0, 16)); // NOI18N

        lblTipoDoc2.setFont(new java.awt.Font("Cantarell", 0, 16)); // NOI18N
        lblTipoDoc2.setText("Teléfono de contacto:");

        txtNumDoc3.setEditable(false);
        txtNumDoc3.setFont(new java.awt.Font("Cantarell", 0, 16)); // NOI18N

        lblFechaIngreso.setFont(new java.awt.Font("Cantarell", 0, 16)); // NOI18N
        lblFechaIngreso.setText("Fecha de Ingreso:");

        txtNumDoc4.setEditable(false);
        txtNumDoc4.setFont(new java.awt.Font("Cantarell", 0, 16)); // NOI18N

        lblDiasReserva.setFont(new java.awt.Font("Cantarell", 0, 16)); // NOI18N
        lblDiasReserva.setText("Días de reserva:");

        btnCambiarReserva.setFont(new java.awt.Font("Cantarell", 0, 16)); // NOI18N
        btnCambiarReserva.setText("Cambiar");

        btnRegistrarServicio.setFont(new java.awt.Font("Cantarell", 0, 16)); // NOI18N
        btnRegistrarServicio.setText("Registrar Servicio");

        btnRegistrarAcompa.setFont(new java.awt.Font("Cantarell", 0, 16)); // NOI18N
        btnRegistrarAcompa.setText("Registrar Acompañante");

        btnVolver.setFont(new java.awt.Font("Cantarell", 0, 16)); // NOI18N
        btnVolver.setText("Volver");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblSubtituloInfoH)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblEstado)
                        .addGap(18, 18, 18)
                        .addComponent(txtEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(48, 48, 48)
                        .addComponent(btnRegistrarEst)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnBorrar))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblTipoDoc)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtTipoDoc, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(lblApellidos)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtApellido, javax.swing.GroupLayout.PREFERRED_SIZE, 401, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblNombre)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 401, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(lblTipoDoc1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtNumDoc, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(lblTipoDoc2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE)
                        .addComponent(txtNumDoc1, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lblTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblFechaIngreso)
                            .addComponent(lblDiasReserva)
                            .addComponent(btnRegistrarServicio))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtNumDoc3, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(txtNumDoc4, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(btnCambiarReserva)
                                        .addGap(42, 42, 42))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(47, 47, 47)
                                .addComponent(btnRegistrarAcompa)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnVolver)))))
                .addContainerGap(28, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(lblTitulo)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEstado)
                    .addComponent(txtEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnRegistrarEst)
                    .addComponent(btnBorrar))
                .addGap(18, 18, 18)
                .addComponent(lblSubtituloInfoH)
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNombre)
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblApellidos)
                    .addComponent(txtApellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTipoDoc)
                    .addComponent(txtTipoDoc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTipoDoc1)
                    .addComponent(txtNumDoc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTipoDoc2)
                    .addComponent(txtNumDoc1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblFechaIngreso)
                    .addComponent(txtNumDoc3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDiasReserva)
                    .addComponent(txtNumDoc4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCambiarReserva))
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRegistrarServicio)
                    .addComponent(btnRegistrarAcompa)
                    .addComponent(btnVolver))
                .addContainerGap(26, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the FlatLaf Light look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        try {
            javax.swing.UIManager.setLookAndFeel(new FlatLightLaf());
        } catch (Exception ex) {
            System.out.println(ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormHabitacion().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBorrar;
    private javax.swing.JButton btnCambiarReserva;
    private javax.swing.JButton btnRegistrarAcompa;
    private javax.swing.JButton btnRegistrarEst;
    private javax.swing.JButton btnRegistrarServicio;
    private javax.swing.JButton btnVolver;
    private javax.swing.JLabel lblApellidos;
    private javax.swing.JLabel lblDiasReserva;
    private javax.swing.JLabel lblEstado;
    private javax.swing.JLabel lblFechaIngreso;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblSubtituloInfoH;
    private javax.swing.JLabel lblTipoDoc;
    private javax.swing.JLabel lblTipoDoc1;
    private javax.swing.JLabel lblTipoDoc2;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JTextField txtApellido;
    private javax.swing.JTextField txtEstado;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtNumDoc;
    private javax.swing.JTextField txtNumDoc1;
    private javax.swing.JTextField txtNumDoc3;
    private javax.swing.JTextField txtNumDoc4;
    private javax.swing.JTextField txtTipoDoc;
    // End of variables declaration//GEN-END:variables
}
