package presentacion;

import entidades.*;
import javax.swing.*;
import java.awt.event.*;
import java.util.ArrayList;
import com.formdev.flatlaf.FlatLightLaf;

/**
 *
 * @author Nícolas Castillo (tecncr@NCR-TOSHIBA)
 */


public class FrmHabilitarHabitacion extends javax.swing.JFrame {

    /**
     * Creates new form FrmHabilitarHabitacion
     */
    public FrmHabilitarHabitacion() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        selectorPiso = new javax.swing.ButtonGroup();
        selectorTipo = new javax.swing.ButtonGroup();
        btnPrimerPiso = new javax.swing.JRadioButton();
        btnSegundoPiso = new javax.swing.JRadioButton();
        btnTercerPiso = new javax.swing.JRadioButton();
        btnCuartoPiso = new javax.swing.JRadioButton();
        lblPiso = new javax.swing.JLabel();
        lblPrecio = new javax.swing.JLabel();
        lblTipo = new javax.swing.JLabel();
        btnSimple = new javax.swing.JRadioButton();
        btnDoble = new javax.swing.JRadioButton();
        btnTriple = new javax.swing.JRadioButton();
        jRadioButton1 = new javax.swing.JRadioButton();
        lblSoles = new javax.swing.JLabel();
        btnRegistrar = new javax.swing.JButton();
        txtSoles = new javax.swing.JFormattedTextField();
        txtCentimos = new javax.swing.JFormattedTextField();
        lblAviso = new javax.swing.JLabel();
        lblPunto = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Dar de alta una Habitación");
        setResizable(false);

        selectorPiso.add(btnPrimerPiso);
        btnPrimerPiso.setFont(btnPrimerPiso.getFont().deriveFont(btnPrimerPiso.getFont().getSize()+2f));
        btnPrimerPiso.setText("Primero");
        btnPrimerPiso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrimerPisoActionPerformed(evt);
            }
        });

        selectorPiso.add(btnSegundoPiso);
        btnSegundoPiso.setFont(btnSegundoPiso.getFont().deriveFont(btnSegundoPiso.getFont().getSize()+2f));
        btnSegundoPiso.setText("Segundo");

        selectorPiso.add(btnTercerPiso);
        btnTercerPiso.setFont(btnTercerPiso.getFont().deriveFont(btnTercerPiso.getFont().getSize()+2f));
        btnTercerPiso.setText("Tercero");

        selectorPiso.add(btnCuartoPiso);
        btnCuartoPiso.setFont(btnCuartoPiso.getFont().deriveFont(btnCuartoPiso.getFont().getSize()+2f));
        btnCuartoPiso.setText("Cuarto");

        lblPiso.setFont(lblPiso.getFont().deriveFont(lblPiso.getFont().getSize()+3f));
        lblPiso.setText("Seleccione el piso de la habitación a habilitar:");

        lblPrecio.setFont(lblPrecio.getFont().deriveFont(lblPrecio.getFont().getSize()+3f));
        lblPrecio.setText("Precio por noche:");

        lblTipo.setFont(lblTipo.getFont().deriveFont(lblTipo.getFont().getSize()+3f));
        lblTipo.setText("Seleccione el tipo de habitación:");

        selectorTipo.add(btnSimple);
        btnSimple.setFont(btnSimple.getFont().deriveFont(btnSimple.getFont().getSize()+2f));
        btnSimple.setText("Simple");

        selectorTipo.add(btnDoble);
        btnDoble.setFont(btnDoble.getFont().deriveFont(btnDoble.getFont().getSize()+2f));
        btnDoble.setText("Doble");

        selectorTipo.add(btnTriple);
        btnTriple.setFont(btnTriple.getFont().deriveFont(btnTriple.getFont().getSize()+2f));
        btnTriple.setText("Triple");

        selectorTipo.add(jRadioButton1);
        jRadioButton1.setFont(jRadioButton1.getFont().deriveFont(jRadioButton1.getFont().getSize()+2f));
        jRadioButton1.setText("Matrimonial");

        lblSoles.setFont(lblSoles.getFont().deriveFont(lblSoles.getFont().getSize()+2f));
        lblSoles.setText("S/");

        btnRegistrar.setFont(btnRegistrar.getFont().deriveFont(btnRegistrar.getFont().getSize()+3f));
        btnRegistrar.setText("Registrar");

        txtSoles.setHorizontalAlignment(javax.swing.JTextField.TRAILING);
        txtSoles.setFont(txtSoles.getFont().deriveFont(txtSoles.getFont().getSize()+2f));
        txtSoles.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSolesActionPerformed(evt);
            }
        });
        txtSoles.setTransferHandler(null);
        txtSoles.addKeyListener(new KeyAdapter() {
            public void keyPressed(KeyEvent ke) {
                String value = txtSoles.getText();
                int l = value.length();
                if ((ke.getKeyChar() >= '0' && ke.getKeyChar() <= '9') || ke.getKeyChar()=='\b') {
                    txtSoles.setEditable(true);
                    lblAviso.setText("");
                } else {
                    txtSoles.setEditable(false);
                    lblAviso.setText("Solo se admiten números");
                }
            }
        });
        txtSoles.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                if(txtSoles.getText().length()>=6&&!(evt.getKeyChar()==KeyEvent.VK_DELETE||evt.getKeyChar()==KeyEvent.VK_BACK_SPACE)) {
                    getToolkit().beep();
                    evt.consume();
                }
            }
        });

        txtCentimos.setFont(txtCentimos.getFont().deriveFont(txtCentimos.getFont().getSize()+2f));
        txtCentimos.setName(""); // NOI18N

        lblAviso.setFont(lblAviso.getFont().deriveFont(lblAviso.getFont().getSize()-3f));

        lblPunto.setFont(lblPunto.getFont().deriveFont(lblPunto.getFont().getSize()+2f));
        lblPunto.setText(".");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(lblPrecio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnSimple)
                                .addGap(29, 29, 29)
                                .addComponent(btnDoble)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGap(29, 29, 29)
                                .addComponent(btnTriple)
                                .addGap(137, 137, 137))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lblSoles)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblAviso, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtSoles))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblPunto, javax.swing.GroupLayout.PREFERRED_SIZE, 4, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtCentimos, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(lblTipo)
                    .addComponent(lblPiso)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnPrimerPiso)
                        .addGap(18, 18, 18)
                        .addComponent(btnSegundoPiso)
                        .addGap(18, 18, 18)
                        .addComponent(btnTercerPiso)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnCuartoPiso))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(284, 284, 284)
                        .addComponent(jRadioButton1)))
                .addContainerGap(25, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnRegistrar)
                .addGap(171, 171, 171))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(lblPiso)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnPrimerPiso)
                    .addComponent(btnSegundoPiso)
                    .addComponent(btnTercerPiso)
                    .addComponent(btnCuartoPiso))
                .addGap(28, 28, 28)
                .addComponent(lblTipo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSimple)
                    .addComponent(btnDoble)
                    .addComponent(btnTriple)
                    .addComponent(jRadioButton1))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPrecio)
                    .addComponent(lblSoles)
                    .addComponent(txtSoles, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCentimos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblPunto))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblAviso, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnRegistrar)
                .addGap(22, 22, 22))
        );

        txtCentimos.setTransferHandler(null);
        txtCentimos.addKeyListener(new KeyAdapter() {
            public void keyPressed(KeyEvent ke) {
                String value = txtCentimos.getText();
                int l = value.length();
                if ((ke.getKeyChar() >= '0' && ke.getKeyChar() <= '9') || ke.getKeyChar()=='\b') {
                    txtCentimos.setEditable(true);
                    lblAviso.setText("");
                } else {
                    txtCentimos.setEditable(false);
                    lblAviso.setText("Solo se admiten números");
                }
            }
        });
        txtCentimos.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                if(txtCentimos.getText().length()>=2&&!(evt.getKeyChar()==KeyEvent.VK_DELETE||evt.getKeyChar()==KeyEvent.VK_BACK_SPACE)) {
                    getToolkit().beep();
                    evt.consume();
                }
            }
        });

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnPrimerPisoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrimerPisoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnPrimerPisoActionPerformed

    private void txtSolesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSolesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSolesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the FlatLaf Light look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        try {
            javax.swing.UIManager.setLookAndFeel(new FlatLightLaf());
        } catch (Exception ex) {
            System.out.println(ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmHabilitarHabitacion().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton btnCuartoPiso;
    private javax.swing.JRadioButton btnDoble;
    private javax.swing.JRadioButton btnPrimerPiso;
    private javax.swing.JButton btnRegistrar;
    private javax.swing.JRadioButton btnSegundoPiso;
    private javax.swing.JRadioButton btnSimple;
    private javax.swing.JRadioButton btnTercerPiso;
    private javax.swing.JRadioButton btnTriple;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JLabel lblAviso;
    private javax.swing.JLabel lblPiso;
    private javax.swing.JLabel lblPrecio;
    private javax.swing.JLabel lblPunto;
    private javax.swing.JLabel lblSoles;
    private javax.swing.JLabel lblTipo;
    private javax.swing.ButtonGroup selectorPiso;
    private javax.swing.ButtonGroup selectorTipo;
    private javax.swing.JFormattedTextField txtCentimos;
    private javax.swing.JFormattedTextField txtSoles;
    // End of variables declaration//GEN-END:variables
}
