package presentacion;

import entidades.*;
import javax.swing.*;
import java.awt.event.*;
import java.util.ArrayList;
import com.formdev.flatlaf.FlatLightLaf;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;

/**
 *
 * @author Nícolas Castillo (tecncr@NCR-TOSHIBA)
 */


public class FrmHabilitarHabitacion extends javax.swing.JFrame {

    /**
     * Creates new form FrmHabilitarHabitacion
     */
    public FrmHabilitarHabitacion() {
        initComponents();
    }
    
    public FrmHabilitarHabitacion(Hotel h) {
        initComponents();
        
        this.h = h;
        
        campos = new ArrayList<>();
        campos.add(txtSoles); campos.add(txtCentimos);
        
        DocumentListener escucharCampos = new DocumentListener() {
            @Override
            public void removeUpdate(DocumentEvent e) { changedUpdate(e); }
            @Override
            public void insertUpdate(DocumentEvent e) { changedUpdate(e); }
            @Override
            public void changedUpdate(DocumentEvent e) {
                boolean habilitarBtn = true;
                    for (JTextField tf : campos) {
                        if (tf.getText().isEmpty()) {
                            habilitarBtn = false;
                        }
                    }
                    btnRegistrar.setEnabled(habilitarBtn);
                }
            };
        for (JTextField tf : campos) {
            tf.getDocument().addDocumentListener(escucharCampos);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        selectorPiso = new javax.swing.ButtonGroup();
        selectorTipo = new javax.swing.ButtonGroup();
        btnPrimerPiso = new javax.swing.JRadioButton();
        btnSegundoPiso = new javax.swing.JRadioButton();
        btnTercerPiso = new javax.swing.JRadioButton();
        btnCuartoPiso = new javax.swing.JRadioButton();
        lblPiso = new javax.swing.JLabel();
        lblPrecio = new javax.swing.JLabel();
        lblTipo = new javax.swing.JLabel();
        btnSimple = new javax.swing.JRadioButton();
        btnDoble = new javax.swing.JRadioButton();
        btnTriple = new javax.swing.JRadioButton();
        btnMatri = new javax.swing.JRadioButton();
        lblSoles = new javax.swing.JLabel();
        btnRegistrar = new javax.swing.JButton();
        txtSoles = new javax.swing.JFormattedTextField();
        txtCentimos = new javax.swing.JFormattedTextField();
        lblAviso = new javax.swing.JLabel();
        lblPunto = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Dar de alta una Habitación");
        setResizable(false);

        selectorPiso.add(btnPrimerPiso);
        btnPrimerPiso.setFont(new java.awt.Font("Cantarell", 0, 15)); // NOI18N
        btnPrimerPiso.setText("Primero");
        btnPrimerPiso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrimerPisoActionPerformed(evt);
            }
        });
        btnPrimerPiso.setSelected(true);

        selectorPiso.add(btnSegundoPiso);
        btnSegundoPiso.setFont(new java.awt.Font("Cantarell", 0, 15)); // NOI18N
        btnSegundoPiso.setText("Segundo");

        selectorPiso.add(btnTercerPiso);
        btnTercerPiso.setFont(new java.awt.Font("Cantarell", 0, 15)); // NOI18N
        btnTercerPiso.setText("Tercero");

        selectorPiso.add(btnCuartoPiso);
        btnCuartoPiso.setFont(new java.awt.Font("Cantarell", 0, 15)); // NOI18N
        btnCuartoPiso.setText("Cuarto");

        lblPiso.setFont(new java.awt.Font("Cantarell", 1, 15)); // NOI18N
        lblPiso.setText("Seleccione el piso de la habitación a habilitar:");

        lblPrecio.setFont(new java.awt.Font("Cantarell", 1, 16)); // NOI18N
        lblPrecio.setText("Precio por noche:");

        lblTipo.setFont(new java.awt.Font("Cantarell", 1, 16)); // NOI18N
        lblTipo.setText("Seleccione el tipo de habitación:");

        selectorTipo.add(btnSimple);
        btnSimple.setFont(new java.awt.Font("Cantarell", 0, 16)); // NOI18N
        btnSimple.setText("Simple");

        selectorTipo.add(btnDoble);
        btnDoble.setFont(new java.awt.Font("Cantarell", 0, 16)); // NOI18N
        btnDoble.setText("Doble");

        selectorTipo.add(btnTriple);
        btnTriple.setFont(new java.awt.Font("Cantarell", 0, 16)); // NOI18N
        btnTriple.setText("Triple");

        selectorTipo.add(btnMatri);
        btnMatri.setFont(new java.awt.Font("Cantarell", 0, 16)); // NOI18N
        btnMatri.setText("Matrimonial");

        lblSoles.setFont(new java.awt.Font("Cantarell", 0, 15)); // NOI18N
        lblSoles.setText("S/");

        btnRegistrar.setFont(new java.awt.Font("Cantarell", 0, 16)); // NOI18N
        btnRegistrar.setText("Registrar");
        btnRegistrar.setEnabled(false);
        btnRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarActionPerformed(evt);
            }
        });

        txtSoles.setHorizontalAlignment(javax.swing.JTextField.TRAILING);
        txtSoles.setFont(new java.awt.Font("Cantarell", 0, 15)); // NOI18N
        txtSoles.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSolesActionPerformed(evt);
            }
        });
        txtSoles.setTransferHandler(null);
        txtSoles.addKeyListener(new KeyAdapter() {
            public void keyPressed(KeyEvent ke) {
                String value = txtSoles.getText();
                int l = value.length();
                if ((ke.getKeyChar() >= '0' && ke.getKeyChar() <= '9') || ke.getKeyChar()=='\b') {
                    txtSoles.setEditable(true);
                    lblAviso.setText("");
                } else {
                    txtSoles.setEditable(false);
                    lblAviso.setText("Solo se admiten números");
                }
            }
        });
        txtSoles.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                if(txtSoles.getText().length()>=6&&!(evt.getKeyChar()==KeyEvent.VK_DELETE||evt.getKeyChar()==KeyEvent.VK_BACK_SPACE)) {
                    getToolkit().beep();
                    evt.consume();
                }
            }
        });

        txtCentimos.setFont(new java.awt.Font("Cantarell", 0, 15)); // NOI18N
        txtCentimos.setName(""); // NOI18N

        lblAviso.setFont(lblAviso.getFont().deriveFont(lblAviso.getFont().getSize()-3f));

        lblPunto.setFont(new java.awt.Font("Cantarell", 0, 15)); // NOI18N
        lblPunto.setText(".");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(lblPrecio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnSimple)
                                .addGap(29, 29, 29)
                                .addComponent(btnDoble)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGap(29, 29, 29)
                                .addComponent(btnTriple)
                                .addGap(137, 137, 137))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lblSoles)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblAviso, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtSoles))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblPunto, javax.swing.GroupLayout.PREFERRED_SIZE, 4, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtCentimos, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(lblTipo)
                    .addComponent(lblPiso)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnPrimerPiso)
                        .addGap(18, 18, 18)
                        .addComponent(btnSegundoPiso)
                        .addGap(18, 18, 18)
                        .addComponent(btnTercerPiso)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnCuartoPiso))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(284, 284, 284)
                        .addComponent(btnMatri)))
                .addContainerGap(25, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnRegistrar)
                .addGap(171, 171, 171))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(lblPiso)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnPrimerPiso)
                    .addComponent(btnSegundoPiso)
                    .addComponent(btnTercerPiso)
                    .addComponent(btnCuartoPiso))
                .addGap(28, 28, 28)
                .addComponent(lblTipo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSimple)
                    .addComponent(btnDoble)
                    .addComponent(btnTriple)
                    .addComponent(btnMatri))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPrecio)
                    .addComponent(lblSoles)
                    .addComponent(txtSoles, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCentimos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblPunto))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblAviso, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnRegistrar)
                .addGap(22, 22, 22))
        );

        btnSimple.setSelected(true);
        txtCentimos.setTransferHandler(null);
        txtCentimos.addKeyListener(new KeyAdapter() {
            public void keyPressed(KeyEvent ke) {
                String value = txtCentimos.getText();
                int l = value.length();
                if ((ke.getKeyChar() >= '0' && ke.getKeyChar() <= '9') || ke.getKeyChar()=='\b') {
                    txtCentimos.setEditable(true);
                    lblAviso.setText("");
                } else {
                    txtCentimos.setEditable(false);
                    lblAviso.setText("Solo se admiten números");
                }
            }
        });
        txtCentimos.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                if(txtCentimos.getText().length()>=2&&!(evt.getKeyChar()==KeyEvent.VK_DELETE||evt.getKeyChar()==KeyEvent.VK_BACK_SPACE)) {
                    getToolkit().beep();
                    evt.consume();
                }
            }
        });

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnPrimerPisoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrimerPisoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnPrimerPisoActionPerformed

    private void txtSolesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSolesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSolesActionPerformed

    private void btnRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarActionPerformed
        Habitacion nuevaHab; TipoHab tipo = TipoHab.SIMPLE; float precio;
        
        precio = Float.parseFloat(txtCentimos.getText())/10 + Float.parseFloat(txtSoles.getText());
        
        if (btnSimple.isSelected()) tipo = TipoHab.SIMPLE;
        if (btnDoble.isSelected()) tipo = TipoHab.DOBLE;
        if (btnTriple.isSelected()) tipo = TipoHab.TRIPLE;
        if (btnMatri.isSelected()) tipo = TipoHab.MATRIMONIAL;
        
        if (btnPrimerPiso.isSelected()){
            h.setContp1(h.getContp1() + 1);
            nuevaHab = new Habitacion(h.getContp1(), Piso.PRIMERO, precio, tipo);
            h.addHab(nuevaHab); JOptionPane.showMessageDialog(null, "Habitación número "+nuevaHab.getNumero()+" añadida.", "Habitación añadida", 1);

        }
        if (btnSegundoPiso.isSelected()){
             h.setContp2(h.getContp2() + 1);
            nuevaHab = new Habitacion(h.getContp2(), Piso.SEGUNDO, precio, tipo);
            h.addHab(nuevaHab); JOptionPane.showMessageDialog(null, "Habitación número "+nuevaHab.getNumero()+" añadida.", "Habitación añadida", 1);

        }
        if (btnTercerPiso.isSelected()){
            h.setContp3(h.getContp3() + 1);
            nuevaHab = new Habitacion(h.getContp3(), Piso.TERCERO, precio, tipo);
            h.addHab(nuevaHab); JOptionPane.showMessageDialog(null, "Habitación número "+nuevaHab.getNumero()+" añadida.", "Habitación añadida", 1);

        }
        if (btnCuartoPiso.isSelected()){
            h.setContp4(h.getContp4() + 1);
            nuevaHab = new Habitacion(h.getContp4(), Piso.CUARTO, precio, tipo);
            h.addHab(nuevaHab); JOptionPane.showMessageDialog(null, "Habitación número "+nuevaHab.getNumero()+" añadida.", "Habitación añadida", 1);
        }
        
    }//GEN-LAST:event_btnRegistrarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the FlatLaf Light look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        try {
            javax.swing.UIManager.setLookAndFeel(new FlatLightLaf());
        } catch (Exception ex) {
            System.out.println(ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmHabilitarHabitacion().setVisible(true);                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton btnCuartoPiso;
    private javax.swing.JRadioButton btnDoble;
    private javax.swing.JRadioButton btnMatri;
    private javax.swing.JRadioButton btnPrimerPiso;
    private javax.swing.JButton btnRegistrar;
    private javax.swing.JRadioButton btnSegundoPiso;
    private javax.swing.JRadioButton btnSimple;
    private javax.swing.JRadioButton btnTercerPiso;
    private javax.swing.JRadioButton btnTriple;
    private javax.swing.JLabel lblAviso;
    private javax.swing.JLabel lblPiso;
    private javax.swing.JLabel lblPrecio;
    private javax.swing.JLabel lblPunto;
    private javax.swing.JLabel lblSoles;
    private javax.swing.JLabel lblTipo;
    private javax.swing.ButtonGroup selectorPiso;
    private javax.swing.ButtonGroup selectorTipo;
    private javax.swing.JFormattedTextField txtCentimos;
    private javax.swing.JFormattedTextField txtSoles;
    // End of variables declaration//GEN-END:variables
    private DocumentListener escucharCampos;
    private Hotel h;
    private ArrayList<JFormattedTextField> campos;
}
