package presentacion;

import entidades.*;
import javax.swing.*;
import java.util.ArrayList;
import com.formdev.flatlaf.FlatLightLaf;
import java.awt.event.*;
public class FrmHabitacion extends javax.swing.JFrame {

    /**
     * Creates new form FormHabitacion
     */
    public FrmHabitacion() {
        initComponents();
    }
    
    public FrmHabitacion(Hotel h, Habitacion hab) {
        initComponents();
        this.h = h;
        this.hab = hab;
    }
    
    private void activarCajas(boolean estado){
        txtNombre.setEditable(estado);
        txtApellido.setEditable(estado);
        txtTipoDoc.setEditable(estado);
        txtNumDoc.setEditable(estado);
        txtTelf.setEditable(estado);
        txtFecha.setEditable(estado);
    }

    private void limpiarCajas(){
        txtNombre.setText(null);
        txtApellido.setText(null);
        txtTipoDoc.setText(null);
        txtNumDoc.setText(null);
        txtTelf.setText(null); 
        txtFecha.setText(null); 
    }
    
    private void actualizarCajas(){
        if (hab.isDisponible())
            txtEstado.setText("Disponible");
        else
            txtEstado.setText("Ocupada");
        
        if(!hab.getHuespedes().isEmpty()){
            txtNombre.setText(hab.getHuespedes().get(0).getNombres());
            txtApellido.setText(hab.getHuespedes().get(0).getApellidos());
            txtTipoDoc.setText(hab.getHuespedes().get(0).getTipoDoc());
            txtNumDoc.setText(hab.getHuespedes().get(0).getNumDoc());
            txtTelf.setText(hab.getHuespedes().get(0).getTelf()); 
            txtFecha.setText(hab.getFechaIngreso());    
        } else {
            limpiarCajas();  
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitulo = new javax.swing.JLabel();
        lblEstado = new javax.swing.JLabel();
        txtEstado = new javax.swing.JTextField();
        btnRegistrarEst = new javax.swing.JButton();
        btnBorrar = new javax.swing.JButton();
        lblSubtituloInfoH = new javax.swing.JLabel();
        lblNombre = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        lblApellidos = new javax.swing.JLabel();
        txtApellido = new javax.swing.JTextField();
        txtTipoDoc = new javax.swing.JTextField();
        lblTipoDoc = new javax.swing.JLabel();
        txtNumDoc = new javax.swing.JTextField();
        lblNumDoc = new javax.swing.JLabel();
        txtTelf = new javax.swing.JTextField();
        lblTelf = new javax.swing.JLabel();
        txtFecha = new javax.swing.JTextField();
        lblFecha = new javax.swing.JLabel();
        txtDiasReserva = new javax.swing.JTextField();
        lblDiasReserva = new javax.swing.JLabel();
        btnRegistrarServicio = new javax.swing.JButton();
        btnRegistrarAcompa = new javax.swing.JButton();
        btnVolver = new javax.swing.JButton();
        btnModificar = new javax.swing.JButton();
        lblAviso = new javax.swing.JLabel();
        lblAvisoGuard = new javax.swing.JLabel();
        btnGuardarAcomp = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Menú de Habitación");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        lblTitulo.setFont(new java.awt.Font("Cantarell", 1, 22)); // NOI18N
        lblTitulo.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblTitulo.setText("Menú de Habitación");

        lblEstado.setFont(new java.awt.Font("Cantarell", 0, 15)); // NOI18N
        lblEstado.setText("Estado:");

        txtEstado.setEditable(false);
        txtEstado.setFont(new java.awt.Font("Cantarell", 0, 15)); // NOI18N

        btnRegistrarEst.setFont(new java.awt.Font("Cantarell", 0, 15)); // NOI18N
        btnRegistrarEst.setText("Registrar Estadía");
        btnRegistrarEst.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarEstActionPerformed(evt);
            }
        });

        btnBorrar.setFont(new java.awt.Font("Cantarell", 0, 15)); // NOI18N
        btnBorrar.setText("Borrar Estadía");
        btnBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBorrarActionPerformed(evt);
            }
        });

        lblSubtituloInfoH.setFont(new java.awt.Font("Cantarell", 1, 10)); // NOI18N
        lblSubtituloInfoH.setText("INFORMACIÓN DEL HUÉSPED PRINCIPAL");

        lblNombre.setFont(new java.awt.Font("Cantarell", 0, 16)); // NOI18N
        lblNombre.setText("Nombre(s):");

        txtNombre.setEditable(false);
        txtNombre.setFont(new java.awt.Font("Cantarell", 0, 16)); // NOI18N

        lblApellidos.setFont(new java.awt.Font("Cantarell", 0, 16)); // NOI18N
        lblApellidos.setText("Apellidos:");

        txtApellido.setEditable(false);
        txtApellido.setFont(new java.awt.Font("Cantarell", 0, 16)); // NOI18N

        txtTipoDoc.setEditable(false);
        txtTipoDoc.setFont(new java.awt.Font("Cantarell", 0, 16)); // NOI18N

        lblTipoDoc.setFont(new java.awt.Font("Cantarell", 0, 16)); // NOI18N
        lblTipoDoc.setText("Tipo de Documento:");

        txtNumDoc.setEditable(false);
        txtNumDoc.setFont(new java.awt.Font("Cantarell", 0, 16)); // NOI18N

        lblNumDoc.setFont(new java.awt.Font("Cantarell", 0, 16)); // NOI18N
        lblNumDoc.setText("Número de Doc. ID:");

        txtTelf.setEditable(false);
        txtTelf.setFont(new java.awt.Font("Cantarell", 0, 16)); // NOI18N

        lblTelf.setFont(new java.awt.Font("Cantarell", 0, 16)); // NOI18N
        lblTelf.setText("Teléfono de contacto:");

        txtFecha.setEditable(false);
        txtFecha.setFont(new java.awt.Font("Cantarell", 0, 16)); // NOI18N

        lblFecha.setFont(new java.awt.Font("Cantarell", 0, 16)); // NOI18N
        lblFecha.setText("Fecha de Ingreso:");

        txtDiasReserva.setEditable(false);
        txtDiasReserva.setFont(new java.awt.Font("Cantarell", 0, 16)); // NOI18N

        lblDiasReserva.setFont(new java.awt.Font("Cantarell", 0, 16)); // NOI18N
        lblDiasReserva.setText("Días de reserva:");

        btnRegistrarServicio.setFont(new java.awt.Font("Cantarell", 0, 16)); // NOI18N
        btnRegistrarServicio.setText("Registrar Servicio");
        btnRegistrarServicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarServicioActionPerformed(evt);
            }
        });

        btnRegistrarAcompa.setFont(new java.awt.Font("Cantarell", 0, 16)); // NOI18N
        btnRegistrarAcompa.setText("Registrar Acompañante");
        btnRegistrarAcompa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarAcompaActionPerformed(evt);
            }
        });

        btnVolver.setFont(new java.awt.Font("Cantarell", 0, 16)); // NOI18N
        btnVolver.setText("Volver");
        btnVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverActionPerformed(evt);
            }
        });

        btnModificar.setFont(new java.awt.Font("Cantarell", 0, 15)); // NOI18N
        btnModificar.setText("Activar Edición");
        btnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarActionPerformed(evt);
            }
        });

        lblAviso.setFont(new java.awt.Font("Cantarell", 0, 10)); // NOI18N

        lblAvisoGuard.setFont(new java.awt.Font("Cantarell", 1, 12)); // NOI18N

        btnGuardarAcomp.setFont(new java.awt.Font("Cantarell", 0, 15)); // NOI18N
        btnGuardarAcomp.setText("Guardar Acompañante");
        btnGuardarAcomp.setEnabled(false);
        btnGuardarAcomp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarAcompActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblEstado)
                                .addGap(18, 18, 18)
                                .addComponent(txtEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(lblSubtituloInfoH))
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnRegistrarEst, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblAvisoGuard, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(151, 151, 151))
                            .addComponent(btnGuardarAcomp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnModificar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnBorrar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 53, Short.MAX_VALUE))))
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnRegistrarServicio)
                        .addGap(59, 59, 59)
                        .addComponent(btnRegistrarAcompa)
                        .addGap(90, 90, 90)
                        .addComponent(btnVolver))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblFecha)
                            .addComponent(lblDiasReserva)
                            .addComponent(lblTipoDoc)
                            .addComponent(lblApellidos)
                            .addComponent(lblNombre)
                            .addComponent(lblNumDoc)
                            .addComponent(lblTelf))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txtApellido, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 401, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 401, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(41, 41, 41)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(txtTipoDoc, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtNumDoc, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtTelf, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lblAviso, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtDiasReserva, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(lblTitulo)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEstado)
                    .addComponent(txtEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnRegistrarEst)
                    .addComponent(btnBorrar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblAvisoGuard, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSubtituloInfoH)
                    .addComponent(btnModificar)
                    .addComponent(btnGuardarAcomp))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblNombre)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtApellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblApellidos))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtTipoDoc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblTipoDoc))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtNumDoc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblNumDoc))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtTelf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblTelf))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblFecha))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtDiasReserva, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblDiasReserva))))
                .addGap(5, 5, 5)
                .addComponent(lblAviso, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRegistrarServicio)
                    .addComponent(btnRegistrarAcompa)
                    .addComponent(btnVolver))
                .addContainerGap(12, Short.MAX_VALUE))
        );

        txtDiasReserva.setTransferHandler(null);
        txtDiasReserva.addKeyListener(new KeyAdapter() {
            public void keyPressed(KeyEvent ke) {
                String value = txtDiasReserva.getText();
                int l = value.length();
                if ((ke.getKeyChar() >= '0' && ke.getKeyChar() <= '9') || ke.getKeyChar()=='\b') {
                    txtDiasReserva.setEditable(true);
                    lblAviso.setText("");
                } else {
                    txtDiasReserva.setEditable(false);
                    lblAviso.setText("Solo se admiten números");
                }
            }
        });
        txtDiasReserva.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                if(txtDiasReserva.getText().length()>=6&&!(evt.getKeyChar()==KeyEvent.VK_DELETE||evt.getKeyChar()==KeyEvent.VK_BACK_SPACE)) {
                    getToolkit().beep();
                    evt.consume();
                }
            }
        });

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        lblTitulo.setText("Habitación "+ hab.getNumero());
        actualizarCajas();
    }//GEN-LAST:event_formWindowOpened

    private void btnVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnVolverActionPerformed

    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed
        activarCajas(true);
    }//GEN-LAST:event_btnModificarActionPerformed

    private void btnBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBorrarActionPerformed
        hab.borrarEstadia();
        actualizarCajas();
        limpiarCajas();
    }//GEN-LAST:event_btnBorrarActionPerformed

    private void btnRegistrarServicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarServicioActionPerformed
        new FrmAddServ(hab).setVisible(true);
    }//GEN-LAST:event_btnRegistrarServicioActionPerformed

    private void btnRegistrarEstActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarEstActionPerformed
        try {
            Huesped huesp = new Huesped(txtNombre.getText(), txtApellido.getText(), txtTipoDoc.getText(), txtNumDoc.getText(), txtTelf.getText());
            if (!hab.getHuespedes().isEmpty())
                hab.setHuespPos(0, huesp);
            else
                hab.addHuesp(huesp);
            hab.setFechaIngreso(txtFecha.getText());
            hab.setDiasReserva(Integer.parseInt(txtDiasReserva.getText()));
            lblAvisoGuard.setText("Estadía registrada");
            activarCajas(false);
            hab.setDisponible(false);
            actualizarCajas();            
        } catch (Exception ex) {
            System.out.println(ex);
            JOptionPane.showMessageDialog(null, "Por favor rellene todos los campos", "Aviso", 2);
        }
    }//GEN-LAST:event_btnRegistrarEstActionPerformed

    private void btnRegistrarAcompaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarAcompaActionPerformed
        limpiarCajas();
        activarCajas(true);
        btnGuardarAcomp.setEnabled(true);
    }//GEN-LAST:event_btnRegistrarAcompaActionPerformed

    private void btnGuardarAcompActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarAcompActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnGuardarAcompActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the FlatLaf Light look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        try {
            javax.swing.UIManager.setLookAndFeel(new FlatLightLaf());
        } catch (Exception ex) {
            System.out.println(ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmHabitacion().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBorrar;
    private javax.swing.JButton btnGuardarAcomp;
    private javax.swing.JButton btnModificar;
    private javax.swing.JButton btnRegistrarAcompa;
    private javax.swing.JButton btnRegistrarEst;
    private javax.swing.JButton btnRegistrarServicio;
    private javax.swing.JButton btnVolver;
    private javax.swing.JLabel lblApellidos;
    private javax.swing.JLabel lblAviso;
    private javax.swing.JLabel lblAvisoGuard;
    private javax.swing.JLabel lblDiasReserva;
    private javax.swing.JLabel lblEstado;
    private javax.swing.JLabel lblFecha;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblNumDoc;
    private javax.swing.JLabel lblSubtituloInfoH;
    private javax.swing.JLabel lblTelf;
    private javax.swing.JLabel lblTipoDoc;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JTextField txtApellido;
    private javax.swing.JTextField txtDiasReserva;
    private javax.swing.JTextField txtEstado;
    private javax.swing.JTextField txtFecha;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtNumDoc;
    private javax.swing.JTextField txtTelf;
    private javax.swing.JTextField txtTipoDoc;
    // End of variables declaration//GEN-END:variables
    private Hotel h;
    private Habitacion hab;
}
