/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Presentacion;

/**
 *
 * @author DIEGO HUAMANJULCA G
 */
public class Jfr_seleccionar_piso_habitacion extends javax.swing.JFrame {

    /**
     * Creates new form Jfr_seleccionar_piso_habitacion
     */
    public Jfr_seleccionar_piso_habitacion() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        P_nombre = new javax.swing.JPanel();
        Lbl_nombre = new javax.swing.JLabel();
        Tf_nombre = new javax.swing.JScrollPane();
        jTextPane1 = new javax.swing.JTextPane();
        Cb_tipodocumento = new javax.swing.JComboBox<>();
        Lbl_Tipodocumento = new javax.swing.JLabel();
        Tp_numerodocumento = new javax.swing.JScrollPane();
        jTextPane2 = new javax.swing.JTextPane();
        Lbl_nacionalidad = new javax.swing.JLabel();
        Tp_nacionalidad = new javax.swing.JScrollPane();
        jTextPane3 = new javax.swing.JTextPane();
        Lbl_Telefono = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Tp_telefono = new javax.swing.JTextPane();
        Rb_1piso = new javax.swing.JRadioButton();
        Lbl_numero_piso = new javax.swing.JLabel();
        Rb_2piso = new javax.swing.JRadioButton();
        Rb_3piso = new javax.swing.JRadioButton();
        Rb_4piso = new javax.swing.JRadioButton();
        jComboBox1 = new javax.swing.JComboBox<>();
        jComboBox2 = new javax.swing.JComboBox<>();
        jComboBox3 = new javax.swing.JComboBox<>();
        jComboBox4 = new javax.swing.JComboBox<>();
        B_agrgacion = new javax.swing.JButton();
        Lbl_Fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Registro\n");
        setResizable(false);

        P_nombre.setPreferredSize(new java.awt.Dimension(700, 293));
        P_nombre.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Lbl_nombre.setFont(new java.awt.Font("Sitka Small", 1, 18)); // NOI18N
        Lbl_nombre.setForeground(new java.awt.Color(255, 255, 255));
        Lbl_nombre.setText("Nombres y apellidos");
        P_nombre.add(Lbl_nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, 230, 20));

        jTextPane1.setBackground(new java.awt.Color(255, 255, 255));
        jTextPane1.setForeground(new java.awt.Color(0, 0, 0));
        Tf_nombre.setViewportView(jTextPane1);

        P_nombre.add(Tf_nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 40, 340, -1));

        Cb_tipodocumento.setBackground(new java.awt.Color(255, 255, 255));
        Cb_tipodocumento.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "DNI", "Pasaporte", "Carta andina", " " }));
        Cb_tipodocumento.setToolTipText("");
        Cb_tipodocumento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Cb_tipodocumentoActionPerformed(evt);
            }
        });
        P_nombre.add(Cb_tipodocumento, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 90, 110, -1));

        Lbl_Tipodocumento.setFont(new java.awt.Font("Sitka Small", 1, 18)); // NOI18N
        Lbl_Tipodocumento.setForeground(new java.awt.Color(255, 255, 255));
        Lbl_Tipodocumento.setText("Tipo de documento");
        P_nombre.add(Lbl_Tipodocumento, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, -1, -1));

        Tp_numerodocumento.setBackground(new java.awt.Color(255, 255, 255));
        Tp_numerodocumento.setForeground(new java.awt.Color(0, 0, 0));

        jTextPane2.setBackground(new java.awt.Color(255, 255, 255));
        jTextPane2.setForeground(new java.awt.Color(0, 0, 0));
        Tp_numerodocumento.setViewportView(jTextPane2);

        P_nombre.add(Tp_numerodocumento, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 90, 160, -1));

        Lbl_nacionalidad.setFont(new java.awt.Font("Sitka Small", 1, 18)); // NOI18N
        Lbl_nacionalidad.setForeground(new java.awt.Color(255, 255, 255));
        Lbl_nacionalidad.setText("Nacionalidad:");
        P_nombre.add(Lbl_nacionalidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, -1, -1));

        Tp_nacionalidad.setBackground(new java.awt.Color(255, 255, 255));

        jTextPane3.setBackground(new java.awt.Color(255, 255, 255));
        jTextPane3.setForeground(new java.awt.Color(0, 0, 0));
        Tp_nacionalidad.setViewportView(jTextPane3);

        P_nombre.add(Tp_nacionalidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 140, 180, -1));

        Lbl_Telefono.setFont(new java.awt.Font("Sitka Small", 1, 18)); // NOI18N
        Lbl_Telefono.setForeground(new java.awt.Color(255, 255, 255));
        Lbl_Telefono.setText("Telefono");
        P_nombre.add(Lbl_Telefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 190, -1, -1));

        jScrollPane1.setBackground(new java.awt.Color(255, 255, 255));

        Tp_telefono.setBackground(new java.awt.Color(255, 255, 255));
        Tp_telefono.setForeground(new java.awt.Color(0, 0, 0));
        jScrollPane1.setViewportView(Tp_telefono);

        P_nombre.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 190, 130, -1));

        Rb_1piso.setFont(new java.awt.Font("Sitka Small", 1, 12)); // NOI18N
        Rb_1piso.setForeground(new java.awt.Color(255, 255, 255));
        Rb_1piso.setText("1°er piso");
        Rb_1piso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Rb_1pisoActionPerformed(evt);
            }
        });
        P_nombre.add(Rb_1piso, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 240, -1, -1));

        Lbl_numero_piso.setBackground(new java.awt.Color(255, 255, 255));
        Lbl_numero_piso.setFont(new java.awt.Font("Sitka Small", 1, 18)); // NOI18N
        Lbl_numero_piso.setForeground(new java.awt.Color(255, 255, 255));
        Lbl_numero_piso.setText("Piso");
        P_nombre.add(Lbl_numero_piso, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 240, 100, -1));

        Rb_2piso.setFont(new java.awt.Font("Sitka Small", 1, 12)); // NOI18N
        Rb_2piso.setForeground(new java.awt.Color(255, 255, 255));
        Rb_2piso.setText("2°do piso");
        P_nombre.add(Rb_2piso, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 240, -1, -1));

        Rb_3piso.setFont(new java.awt.Font("Sitka Small", 1, 12)); // NOI18N
        Rb_3piso.setForeground(new java.awt.Color(255, 255, 255));
        Rb_3piso.setText("3°er piso");
        P_nombre.add(Rb_3piso, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 240, -1, -1));

        Rb_4piso.setFont(new java.awt.Font("Sitka Small", 1, 12)); // NOI18N
        Rb_4piso.setForeground(new java.awt.Color(255, 255, 255));
        Rb_4piso.setText("4°to piso");
        P_nombre.add(Rb_4piso, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 240, -1, -1));

        jComboBox1.setBackground(new java.awt.Color(255, 255, 255));
        jComboBox1.setForeground(new java.awt.Color(0, 0, 0));
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", " " }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        P_nombre.add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 260, -1, -1));

        jComboBox2.setBackground(new java.awt.Color(255, 255, 255));
        jComboBox2.setForeground(new java.awt.Color(0, 0, 0));
        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "8", "9", "10", "11", "12", "13", "14", " " }));
        P_nombre.add(jComboBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 260, -1, -1));

        jComboBox3.setBackground(new java.awt.Color(255, 255, 255));
        jComboBox3.setForeground(new java.awt.Color(0, 0, 0));
        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "15", "16", "17", "18", "19", "20", "21", "22" }));
        P_nombre.add(jComboBox3, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 260, -1, -1));

        jComboBox4.setBackground(new java.awt.Color(255, 255, 255));
        jComboBox4.setForeground(new java.awt.Color(0, 0, 0));
        jComboBox4.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "23", "24", "25", "26", "27", "28", "29", "30" }));
        P_nombre.add(jComboBox4, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 260, -1, -1));

        B_agrgacion.setBackground(new java.awt.Color(255, 255, 255));
        B_agrgacion.setFont(new java.awt.Font("Sitka Small", 1, 14)); // NOI18N
        B_agrgacion.setForeground(new java.awt.Color(0, 0, 0));
        B_agrgacion.setText("Agregar acompañantes");
        B_agrgacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B_agrgacionActionPerformed(evt);
            }
        });
        P_nombre.add(B_agrgacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 300, -1, -1));

        Lbl_Fondo.setBackground(new java.awt.Color(255, 255, 255));
        Lbl_Fondo.setForeground(new java.awt.Color(255, 255, 255));
        Lbl_Fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/unnamed.jpg"))); // NOI18N
        P_nombre.add(Lbl_Fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(P_nombre, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(P_nombre, javax.swing.GroupLayout.DEFAULT_SIZE, 478, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Cb_tipodocumentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Cb_tipodocumentoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Cb_tipodocumentoActionPerformed

    private void Rb_1pisoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Rb_1pisoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Rb_1pisoActionPerformed

    private void B_agrgacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B_agrgacionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_B_agrgacionActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Jfr_seleccionar_piso_habitacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Jfr_seleccionar_piso_habitacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Jfr_seleccionar_piso_habitacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Jfr_seleccionar_piso_habitacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Jfr_seleccionar_piso_habitacion().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton B_agrgacion;
    private javax.swing.JComboBox<String> Cb_tipodocumento;
    private javax.swing.JLabel Lbl_Fondo;
    private javax.swing.JLabel Lbl_Telefono;
    private javax.swing.JLabel Lbl_Tipodocumento;
    private javax.swing.JLabel Lbl_nacionalidad;
    private javax.swing.JLabel Lbl_nombre;
    private javax.swing.JLabel Lbl_numero_piso;
    private javax.swing.JPanel P_nombre;
    private javax.swing.JRadioButton Rb_1piso;
    private javax.swing.JRadioButton Rb_2piso;
    private javax.swing.JRadioButton Rb_3piso;
    private javax.swing.JRadioButton Rb_4piso;
    private javax.swing.JScrollPane Tf_nombre;
    private javax.swing.JScrollPane Tp_nacionalidad;
    private javax.swing.JScrollPane Tp_numerodocumento;
    private javax.swing.JTextPane Tp_telefono;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JComboBox<String> jComboBox3;
    private javax.swing.JComboBox<String> jComboBox4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextPane jTextPane1;
    private javax.swing.JTextPane jTextPane2;
    private javax.swing.JTextPane jTextPane3;
    // End of variables declaration//GEN-END:variables
}
