/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Presentacion;

/**
 *
 * @author DIEGO HUAMANJULCA G
 */
public class Jfr_acompañante extends javax.swing.JFrame {

    /**
     * Creates new form Jfr_acompañante
     */
    public Jfr_acompañante() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        P_fondo = new javax.swing.JPanel();
        lBL_NOMBREAPELLIDOS = new javax.swing.JLabel();
        Tp_nombre = new javax.swing.JScrollPane();
        jTextPane1 = new javax.swing.JTextPane();
        Lbl_fondo = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Registo acompañantes");

        P_fondo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lBL_NOMBREAPELLIDOS.setFont(new java.awt.Font("Sitka Small", 1, 14)); // NOI18N
        lBL_NOMBREAPELLIDOS.setForeground(new java.awt.Color(51, 51, 255));
        lBL_NOMBREAPELLIDOS.setText("Nombre y Apellidos");
        P_fondo.add(lBL_NOMBREAPELLIDOS, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, -1, -1));

        Tp_nombre.setBackground(new java.awt.Color(255, 255, 255));

        jTextPane1.setBackground(new java.awt.Color(255, 255, 255));
        jTextPane1.setForeground(new java.awt.Color(0, 0, 0));
        Tp_nombre.setViewportView(jTextPane1);

        P_fondo.add(Tp_nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 60, 260, -1));

        Lbl_fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/road-to-mountains-hd-1080x1920-1.jpg"))); // NOI18N
        P_fondo.add(Lbl_fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jLabel1.setText("jLabel1");
        P_fondo.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(P_fondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(P_fondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Jfr_acompañante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Jfr_acompañante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Jfr_acompañante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Jfr_acompañante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Jfr_acompañante().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Lbl_fondo;
    private javax.swing.JPanel P_fondo;
    private javax.swing.JScrollPane Tp_nombre;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextPane jTextPane1;
    private javax.swing.JLabel lBL_NOMBREAPELLIDOS;
    // End of variables declaration//GEN-END:variables
}
